### ISSUE TITLE
git pull gives "fatal: refusing to merge unrelated histories"

### ISSUE THREAD

**Issue by ErikDeBruijn** [jnuyens/freedomev#12]
With a fresh download (from yesterday) of the USB rootfs I tried to `git pull` from the Model S within the chroot, but got the following:
```root@cid:/# git pull
remote: Enumerating objects: 368, done.
remote: Counting objects: 100% (368/368), done.
remote: Compressing objects: 100% (147/147), done.
remote: Total 606 (delta 220), reused 366 (delta 219), pack-reused 238
Receiving objects: 100% (606/606), 110.58 KiB | 501.00 KiB/s, done.
Resolving deltas: 100% (274/274), completed with 49 local objects.
From https://github.com/jnuyens/freedomev
 + 3e5aace...b6fed87 master      -> origin/master  (forced update)
 * [new branch]      new_toggles -> origin/new_toggles
fatal: refusing to merge unrelated histories
```
I'm not sure what's going on, but I'll hold off installing it for now.

**Comment by ErikDeBruijn** [comment]
Note, it actually did pull and update the files, so perhaps we could close this...

**Comment by jnuyens** [comment]
I did indeed rewrite history and that's annoying. I should generate a new image file, indeed to prevent that from happening.

**Comment by jnuyens** [comment]
I'll close after I put that online. And will bump the version to 1.1

**Comment by maslakandrey** [comment]
good afternoon, how to contact you? write e-mail or write me maslakandrey@gmail.com

**Comment by appleguru** [comment]
I did a _git reset --hard origin/master_ to resolve this, but I'm unsure if that will cause other issues.

**Comment by jnuyens** [comment]
Should be ok since I rewrote history. Still need to bump the version and create a new image to make it easier, sry for the delay.

**Comment by jnuyens** [comment]
I bumped the version to 1.1, so if you enable auto-updating, it should do git pull and get the new simple feature to lock and unlock the service port.

**Comment by maslakandrey** [comment]
I can not understand why my computer does not see the cid of the machine, I
think the problem is in the computer





пт, 11 окт. 2019 г. в 01:01, Jasper Nuyens <notifications@github.com>:

**Comment by jnuyens** [comment]
Dear,

If you try connecting from the service port below the cid, this is expected behavior: the iptables rules on cid block it and also the port is disabled on the gateway. 
If you have root already and FreedomEV is running, you should be able to lock and unlock the port through the interface. It does require socat on the image, I'll add package dependencies to version 1.3 to ensure it's there. 

Grtz, 
Jasper

**Comment by maslakandrey** [comment]
That here the problem is that there is no access root :(

пт, 11 окт. 2019 г. в 10:51, Jasper Nuyens <notifications@github.com>:
