### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by 0x77dev** [jnuyens/freedomev#15]
### How to ssh to the **CID**?
Asking for help, please reply as soon as possible...

**Comment by JosDeGraeve** [comment]
In order to get a reply as soon as possible, i'd recommend google:

https://lmgtfy.com/?q=tesla+howto+ssh+to+the+CID

seriously, the best way to obtain the required information is to wade through a few forums.  Things depend on a lot of factors like what model/year you're having etc.  The process is not easy and you gonna need to do your research.

**Comment by jnuyens** [comment]
Try to gain access to the IC first; as that's an 'accepted way' by Tesla in case one gets physical access to the network. CID access is more complex and for certain cars and/or software releases there are no publicly (or otherwise) known ways.

**Comment by 0x77dev** [comment]
I have physical access, I can’t configure connection, how to setup (IP,netmask, etc...) I cannot obtain ip from dhcp...

**Comment by jnuyens** [comment]
Take a look at one of the online presentations. You need a fixed IP, there is no dhcp server active on this network.

**Comment by ErikDeBruijn** [comment]
> I have physical access, I can’t configure connection, how to setup (IP,netmask, etc...) I cannot obtain ip from dhcp...

How you do this depends on your OS, but you can create an IP in a `/24` range: 192.168.90.99.

`/24` means a netmask of `255.255.255.0`. Keep the normal default route of your internet uplink to your laptop.

**Comment by 0x77dev** [comment]
So I can use these parameters?:
* netmask: ` 255.255.255.0 `
* gateway: ` 192.168.90.1 `
* my ip: ` 192.168.90.99 `
P.S. Im using Linux

**Comment by 0x77dev** [comment]
oh, gateway: ` 192.168.90.102`
That's all, thanks!

**Comment by ErikDeBruijn** [comment]
Actually, the "default route" is also called the "gateway/route of last resort" (gateway in short), but that's not the same thing as a system on the Tesla's network also called a "gateway". You should not confuse the two. A Tesla's gateway is a specific computer designed to isolate vehicle safety affecting parts from the infotainment stuff. E.g. you shouldn't be able to artificially "hit the accellerator" or control steering from the network that infotainment is part of.

**Comment by 0x77dev** [comment]
I understand.

Вкл пн, сент. 9, 2019 в 14:10, Erik de Bruijn <notifications@github.com> пишет:
