### ISSUE TITLE
Awesome project! Would it work with a Japan imported Nissan Leaf 2013?

### ISSUE THREAD

**Issue by mahalel** [jnuyens/freedomev#7]

**Comment by ErikDeBruijn** [comment]
Right now this is very specific to the software running on Model S or X's computers. Sorry!

Making this work with another brand/technology would be very hard, easier to start an entirely new project.

**Comment by jnuyens** [comment]
I also want to add that a minimum requirement is that it should run the Linux kernel. Unsure about that with the Leaf. An eMMC dump can rule that out.
